version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
